apiVersion: v1
kind: Secret
metadata:
  name: flashcard-postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: flashcard
  POSTGRES_USER: flashcard
  POSTGRES_PASSWORD: flashcard
  DATABASE_URL: postgresql+psycopg://flashcard:flashcard@postgres:5432/flashcard
